const data = {
  product: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      categories: "Shirt",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirts",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      categories: "Shirt",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirts",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      categories: "Pant",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality pant",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      categories: "Pant",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality pant",
    },
  ],
};
export default data;
